class DateIdeasController < ApplicationController
  def index
    # This is now your main input form page
  end

  def generate
    # This will handle the form submission and generate the date idea
    @preferences = {
      budget: params[:budget],
      time_of_day: params[:time_of_day],
      setting: params[:setting],
      effort: params[:effort],
      location: params[:location],
      additional_notes: params[:additional_notes]
    }
    
    # For now, let's create a mock response (we'll add ChatGPT later)
    @generated_date = create_mock_date(@preferences)
    
    render :result
  end

  def show
    @date_idea = DateIdea.find(params[:id])
  end

  private

  def create_mock_date(preferences)
    # Mock response - we'll replace this with ChatGPT API call
    {
      title: "Surprise Date in #{preferences[:location]}",
      description: "Based on your preferences for #{preferences[:time_of_day]} #{preferences[:setting]} activity with #{preferences[:effort]} effort level.",
      budget: estimate_budget(preferences[:budget]),
      time_of_day: preferences[:time_of_day],
      setting: preferences[:setting],
      effort: preferences[:effort],
      location: preferences[:location],
      detailed_plan: "Here's your surprise date plan! (This will be generated by ChatGPT)"
    }
  end

  def estimate_budget(budget_range)
    case budget_range
    when 'free' then 0
    when 'low' then 25
    when 'medium' then 100
    when 'high' then 200
    when 'luxury' then 400
    else 50
    end
  end
end
